# Define the default logger level
log4j.logger.ros=INFO

# Override specific loggers to hide warnings
log4j.logger.ros.tf2_ros=ERROR
log4j.logger.ros.tf2=ERROR
# Si SLAM toolbox fait des siennes (359/360) : 
log4j.logger.ros.slam_toolbox=INFO
